### ISSUE TITLE
RSXML: log.setup with no log_level returns error

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RiverscapesXML#698]
```python

log.setup(log_path=os.path.join(merged_folder, 'merge-projects.log'))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/.local/lib/python3.11/site-packages/rsxml/logging/logger.py", line 183, in setup
    self.instance.setup(**kwargs)
  File "/home/vscode/.local/lib/python3.11/site-packages/rsxml/logging/logger.py", line 66, in setup
    self.verbose = verbose if verbose else log_level >= logging.DEBUG
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

```

**Comment by MattReimer** [comment]
This is fixed. Also rsxml has it's own repo now
https://github.com/Riverscapes/rsxml-python
